FROM maven:3.9-eclipse-temurin-21-alpine AS build
WORKDIR /app
COPY . .
RUN mvn clean package -pl monitoring-service -am -DskipTests

FROM eclipse-temurin:21-jre-jammy
WORKDIR /app
COPY --from=build /app/monitoring-service/target/*.jar app.jar

ENTRYPOINT ["sh", "-c", "java -Xmx300m -Dserver.port=$PORT -jar app.jar"]