FROM maven:3.9-eclipse-temurin-21-alpine AS build
WORKDIR /app
COPY . .
RUN mvn clean package -pl registry-service -am -DskipTests

FROM eclipse-temurin:21-jre-jammy
WORKDIR /app
COPY --from=build /app/registry-service/target/*.jar app.jar
EXPOSE 8761
ENTRYPOINT ["sh", "-c", "java -Xmx300m -Dserver.port=${PORT:-8761} -jar app.jar"]