server:
  port: ${PORT:8081}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME:dummy}
    password: ${SMTP_PASSWORD:dummy}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true