server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/jhachhotu/sentinel-config-repo
          default-label: main
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

  instance:
    prefer-ip-address: true